package com.abctreinamentos;

import java.sql.Date;

// Generated 1 de nov. de 2022 07:17:19 by Hibernate Tools 4.3.6.Final

/**
 * Pagamentos generated by hbm2java
 */
public class Pagamentos implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPagamento;
	private Integer fk_cliente;
	private Integer fk_curso;
	private Date data;
	
	public Integer getIdPagamento() {
		return this.idPagamento;
	}

	public void setIdPagamento(Integer idPagamento) {
		this.idPagamento = idPagamento;
	}

	public Integer getFk_cliente() {
		return fk_cliente;
	}

	public void setFk_cliente(Integer fk_cliente) {
		this.fk_cliente = fk_cliente;
	}

	public Integer getFk_curso() {
		return fk_curso;
	}

	public void setFk_curso(Integer fk_curso) {
		this.fk_curso = fk_curso;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
